Component slots
clarkmcc/ngraph pull request #35
Opened 2024-02-10 21:08 UTC by sroussey

Rebased to main and then added more slots and made them available to custom nodes.

2024-02-11 00:26 UTC, clarkmcc commented
Is this ready for review? I didn't want to dive in if you're not happy with it yet, but I did see your reference comment on the other issue.

2024-02-11 05:10 UTC, sroussey commented
Yeah, it is working so far. 

I have more ideas, but don't think I'll get to them for a while.

2024-02-11 19:08 UTC, clarkmcc requested changes
Can you run prettier? There's a config already in the project.

2024-02-11 19:08 UTC, clarkmcc commented on lib/node-builder.tsx
> +  inputGroups: React.JSX.Element[]
What's the use-case for distinguishing between `inputs` and `inputGroups`? Can they be safely treated as the same thing?

2024-02-11 23:36 UTC, sroussey commented on lib/node-builder.tsx
> +  inputGroups: React.JSX.Element[]
oh, sure. I was really just replicated what you had. Not sure anyone would ever want to reverse them!

2024-02-11 23:37 UTC, sroussey commented
> Can you run prettier? There's a config already in the project.

Really? I've been going nuts without it since there is no .vscode folder for this project

2024-02-12 01:45 UTC, clarkmcc commented on lib/node-builder.tsx
> +  inputGroups: React.JSX.Element[]
I think they need to be generated separately, but it sounds like they can safely just be combined into a single inputs slot

2024-02-12 01:47 UTC, clarkmcc commented
Yeah I don't use vscode but having the config in the project is fine with me. I do think there's a few IDE-agnostic config files all at the root including a prettier setup.

Thanks for running the formatter! Will take a final look at this tomorrow.

2024-02-12 13:30 UTC, clarkmcc approved these changes

2024-02-12 14:01 UTC, merged